name: Build UploadToNAS

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  
  release:
    types: [published]

  push:
    branches: 
      - master
    paths:
      - '.github/workflows/UploadToNAS.yml'

  schedule:
    - cron: 0 7 * * 5

env:
  TZ: Asia/Shanghai
  ftp_username: ${{ secrets.FTP_USERNAME }}
  ftp_psw: ${{ secrets.FTP_PSW }}
  ftp_ip: ${{ secrets.FTP_IP }}
  ftp_port: ${{ secrets.FTP_PORT }}
  TargetPath: openwrt
  upload_file_1: FixSynoboot.sh

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Upload firmware to my NAS
      id: gx-nas
      run: |
        curl -SLO https://wp.gxnas.com/wp-content/uploads/2020/07/FixSynoboot.sh
        echo $ftp_psw >> /tmp/rsync.psw 
        chmod 600 /tmp/rsync.psw
        rsync -azvP -e $ftp_port --password-file=/tmp/rsync.psw $upload_file_1 rsync://$ftp_username@$ftp_ip:/$TargetPath/
        echo "All Released Files Uploaded to GXNAS"

    - name: WeChat notification
      run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=UploadToNAS 编译结束！
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 30
        keep_minimum_runs: 4
